from typing import List

class SmartDL:
    def __init__(self, url: str, dest: str, progress_bar: bool = ..., timeout: float = ...) -> None: ...
    def start(self, blocking: bool = ...) -> None: ...
    def isFinished(self) -> bool: ...
    def isSuccessful(self) -> bool: ...
    def wait(self, raise_exceptions: bool = ...) -> None: ...
    def get_errors(self) -> List[Exception]: ...
    def get_dest(self) -> str: ...
    def get_dl_size(self) -> int: ...
    filesize: int
