from typing import Callable, List

class SmartDL:
    def __init__(self, url: str, dest: str, progress_bar: bool = ..., timeout: float = ...) -> None: ...
    def add_progress_hook(self, hook: Callable[["SmartDL"], None]) -> None: ...
    def start(self, blocking: bool = ...) -> None: ...
    def isSuccessful(self) -> bool: ...
    def get_errors(self) -> List[Exception]: ...
    def get_dest(self) -> str: ...
    def get_dl_size(self) -> int: ...
    filesize: int
