from typing import Any, Type

class HTML:
    html: str
    def render(self, *, timeout: float | None = ..., sleep: float | None = ...) -> None: ...

class HTMLResponse:
    html: HTML

class HTMLSession:
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    def get(self, url: str, *, headers: dict[str, str] | None = ..., timeout: float | None = ...) -> HTMLResponse: ...
    def close(self) -> None: ...
    def __enter__(self) -> HTMLSession: ...
    def __exit__(self, exc_type: Type[BaseException] | None, exc: BaseException | None, tb: Any) -> bool: ...
